# Generated by Django 5.0.2 on 2025-01-03 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.FloatField()),
                ('precio_alquiler', models.FloatField(blank=True, null=True)),
                ('anyo_construccion', models.PositiveIntegerField()),
                ('surface', models.PositiveIntegerField()),
                ('bathrooms', models.PositiveIntegerField()),
                ('rooms', models.PositiveIntegerField()),
                ('tipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.tipo')),
            ],
        ),
    ]
