# Generated by Django 5.0.2 on 2024-12-26 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.IntegerField()),
                ('kilometros', models.PositiveIntegerField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen', models.URLField()),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.marca')),
            ],
        ),
    ]
